name: postgresql
values:
  passwords:
    - name: password
      description: "Password for the postgres account."
      print: true
      length: 16
      numDigits: 5
      numSymbols: 0
      noUpper: false
      allowRepeat: false
encryption:
  enabled: true
  inputPaths:
    - base/secret.yaml
