apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: {{index . "namespace"}}
spec:
  serviceAccountName: {{index . "serviceAccountName"}}
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "11.1.25"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    auth:
      existingSecret: postgresql-secret
